FLAGS = -ansi -Wall -Wextra -Werror -pedantic-errors
LIBS = -lm

all: spmat.o linkedlist.o submat.o powerIteration.o division.o prog.o   
	gcc $(FLAGS) spmat.o linkedlist.o submat.o powerIteration.o division.o prog.o -o cluster $(LIBS)
clean:
	rm -rf *.o cluster

spmat.o: spmat.c
	gcc $(FLAGS) -c spmat.c
linkedlist.o: linkedlist.c
	gcc $(FLAGS) -c linkedlist.c
submat.o: submat.c
	gcc $(FLAGS) -c submat.c
powerIteration.o: powerIteration.c
	gcc $(FLAGS) -c powerIteration.c
division.o: division.c
	gcc $(FLAGS) -c division.c
prog.o: prog.c
	gcc $(FLAGS) -c prog.c

